### ISSUE TITLE
 rfft()

### ISSUE THREAD

**Issue by nooorris** [funcwj/cgmm-mask-estimator#1]
# cgmm_mask_estimate.m 
37     ...
38     spectrums(:, :, c) = rfft(frames_padding, fft_length, 2);
39     ...
# end 
It seems that the function rfft() is not a valid function of Matlab in line 38 of the cgmm_mask_estimate.m file.

**Comment by funcwj** [comment]
Install [voicebox](http://www.ee.ic.ac.uk/hp/staff/dmb/voicebox/voicebox.html) first.
